@startuml CG_Template

title Diagrama de Classes
footer Computação Gráfica

!include ../../CG_Biblioteca/docs/umlClasses.wsd

Mundo : camera
Mundo : objetosLista[]
Mundo : moverPto
Mundo : retanguloA
Mundo : retanguloB
Mundo : OnLoad()
Mundo : OnUpdateFrame()
Mundo : OnRenderFrame()
Mundo : OnKeyDown()
Mundo : OnMouseMove()
Mundo : Sru3D()
Camera <-left- Mundo

Objeto : rotulo
Objeto : primitivaTipo
Objeto : PrimitivaTipo()
Objeto : primitivaTamanho
Objeto : PrimitivaTamanho()
Objeto : Desenhar()
Objeto : DesenharAramado()
Objeto <-down- Mundo

ObjetoAramado : pontosLista[]
ObjetoAramado : DesenharAramado()
ObjetoAramado : PontosAdicionar(pto)
ObjetoAramado : PontosRemoverTodos()
ObjetoAramado <-down- Objeto

Ponto4D <-right- ObjetoAramado

Retangulo : ptoInferiorEsquerdo
Retangulo : ptoSuperiorDireito
Retangulo : MoverPtoSuperiorDireito()
Retangulo : MoverPtoSuperiorDireito(ptoMover)
Retangulo <|- ObjetoAramado

@enduml
