@startuml

@startuml

!include ../../CG_Biblioteca/docs/umlClasses.wsd

Mundo : Camera
Mundo : Objeto[]
Mundo : objetoSelecionado
Mundo : pegarObjetoSelecionado()
Camera <-left- Mundo

Objeto : cor
Objeto : mudarCor()
Objeto : primitiva
Objeto : mudarPrimitiva()
Objeto : Ponto4D[]
Objeto : Objeto[]
Objeto <|-up- Mundo
Transformacao4D <-right- Objeto
BBox <-down- Objeto
Ponto4D <-Objeto

@enduml
