@startuml

title Diagrama de Casos de Uso
footer Computação Gráfica

(Função 1) as fu1
usecase "Função 2" as fu2
usecase "Função 3" as fu3

:Ator 1: as at1
actor "Ator 2" as at2

at1 -> fu1
at1 -up-> fu2

at2 -> fu3

at1 <|-- at2

@enduml
