@startuml

@startuml

title Diagrama de Classes
footer Computação Gráfica

!include ../../CG_Biblioteca/docs/umlClasses.wsd

Mundo : Camera
Mundo : Objeto[]
Mundo : objetoSelecionado
Mundo : pegarObjetoSelecionado()
Camera <-left- Mundo

Objeto : cor
Objeto : mudarCor()
Objeto : primitiva
Objeto : mudarPrimitiva()
Objeto : Ponto4D[]
Objeto : Objeto[]
Objeto <-down- Mundo
Transformacao4D <-right- Objeto
BBox <-down- Objeto
Ponto4D <-down- Objeto

Circulo : Raio
Circulo : ptoCentro
Circulo <|- Objeto

@enduml
