/' http://plantuml.com/class-diagram '/ 
@startuml CG_Biblioteca

BBox : double menorX
BBox : double menorY
BBox : double menorZ
BBox : double maiorX
BBox : double maiorY
BBox : double maiorZ
BBox : Ponto4D centro
BBox : BBox(double menorX, double menorY, double menorZ, double maiorX, double maiorY, double maiorZ)
BBox : void atribuirBBox(Ponto4D pto)	
BBox : void atualizarBBox(Ponto4D pto)
BBox : void atualizarBBox(double x, double y, double z)
BBox : void processarCentroBBox()
BBox : void desenhaBBox()
BBox : double obterMenorX
BBox : double obterMenorY
BBox : double obterMenorZ
BBox : double obterMaiorX
BBox : double obterMaiorY
BBox : double obterMaiorZ
BBox : Ponto4D obterCentro
BBox o-- Ponto4D

Camera : double xMin
Camera : double xMax
Camera : double yMin
Camera : double yMax
Camera : double zMin
Camera : double zMax
Camera : Camera(double xMin,double xMax,double yMin,double yMax,double zMin, double zMax)
Camera : double xmin
Camera : double xmax
Camera : double ymin
Camera : double ymax
Camera : double zmin
Camera : double zmax
Camera : void panEsq()
Camera : void panDir()
Camera : void panCim()
Camera : void panBai()
Camera : void zoomIn()
Camera : void zoomOut()

Matematica : Ponto4D ptoCirculo(double angulo, double raio)
Matematica : double ptoCirculoSimétrico(double raio)

Ponto4D : double x;
Ponto4D : double y;
Ponto4D : double z;
Ponto4D : readonly double w;
Ponto4D : Ponto4D(double x, double y, double z, double w)
Ponto4D : Ponto4D(Ponto4D pto) {
Ponto4D : double X
Ponto4D : double Y
Ponto4D : double Z
Ponto4D : double W
Ponto4D : void inverterSinal()

Transformacao4D : {static} + readonly double DEG_TO_RAD
Transformacao4D : -double[4x4] matriz
Transformacao4D : +Transformacao4D()
Transformacao4D : +void AtribuirIdentidade()
Transformacao4D : +void AtribuirTranslacao(double tx, double ty, double tz)
Transformacao4D : +void AtribuirEscala(double sX, double sY, double sZ)
Transformacao4D : +void AtribuirRotacaoX(double radians)
Transformacao4D : +void AtribuirRotacaoY(double radians)
Transformacao4D : +void AtribuirRotacaoZ(double radians)
Transformacao4D : +Ponto4D TransformPoint(Ponto4D pto)
Transformacao4D : +Transformacao4D TransformMatrix(Transformacao4D t)
Transformacao4D : +double GetElement(int index)
Transformacao4D : +void SetElement(int index, double value)
Transformacao4D : +double[] GetDate()
Transformacao4D : +void SetData(double[] data)
Transformacao4D : +void ExibeMatriz()

@enduml
